//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BagisiklikTakipSistemi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PostTablosu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PostTablosu()
        {
            this.YorumlarTablosu = new HashSet<YorumlarTablosu>();
        }
    
        public int ID { get; set; }
        public Nullable<int> UyeID { get; set; }
        public string PostBaslik { get; set; }
        public string PostIcerik { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public Nullable<bool> Durum { get; set; }
    
        public virtual UyelerTablosu UyelerTablosu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<YorumlarTablosu> YorumlarTablosu { get; set; }
    }
}
