//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BagisiklikTakipSistemi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UyelerTablosu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UyelerTablosu()
        {
            this.PostTablosu = new HashSet<PostTablosu>();
            this.TuketimTablosu = new HashSet<TuketimTablosu>();
            this.YorumlarTablosu = new HashSet<YorumlarTablosu>();
        }
    
        public int ID { get; set; }
        public string KulAdi { get; set; }
        public string KulSoyadi { get; set; }
        public string Sifre { get; set; }
        public Nullable<int> Yetki { get; set; }
        public string Mail { get; set; }
        public string Telefon { get; set; }
        public Nullable<decimal> Boy { get; set; }
        public Nullable<int> Yas { get; set; }
        public Nullable<decimal> Kilo { get; set; }
        public Nullable<bool> Durum { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PostTablosu> PostTablosu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TuketimTablosu> TuketimTablosu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<YorumlarTablosu> YorumlarTablosu { get; set; }
    }
}
