//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BagisiklikTakipSistemi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class YorumlarTablosu
    {
        public int ID { get; set; }
        public Nullable<int> PostID { get; set; }
        public Nullable<int> UyeID { get; set; }
        public string YorumBaslik { get; set; }
        public string YorumIcerik { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public Nullable<bool> Durum { get; set; }
    
        public virtual PostTablosu PostTablosu { get; set; }
        public virtual UyelerTablosu UyelerTablosu { get; set; }
    }
}
